"""empty message

Revision ID: 48230b625bc2
Revises: 4589b9a38b1c
Create Date: 2018-12-29 17:29:14.207024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48230b625bc2'
down_revision = '4589b9a38b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teacher', 'course', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='foreignkey')
    op.drop_column('teacher', 'course_id')
    # ### end Alembic commands ###
