"""empty message

Revision ID: b56e01bac4ee
Revises: 477bbbfb48d6
Create Date: 2018-12-28 11:14:36.963527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56e01bac4ee'
down_revision = '477bbbfb48d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uage', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('uemail', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uemail')
    op.drop_column('user', 'uage')
    # ### end Alembic commands ###
